.TH textgen 3 "March 13, 2018" "" "textgen"

.SH НАЗВАНИЕ
textgen \- простой генератор случайных текстов на основе существующего текста

.SH СИНТАКСИС
.B textgen  [-vhfdce] [--help --version]
.br

.SH ОПИСАНИЕ
Опции:
.RS 4
-h или --help - вывести справку
.RE
.RS 4
-v или --version - вывести информацию о версии
.RE
.RS 4
-f=filename - файл с базовым текстом
.RE
.RS 4
-d - размер n-граммы
.RE
.RS 4
-e - кодировка файла
.RE
.RS 4
-с - число предложений
.RE


